name: Pull Request Pipeline

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq 

      - name: Install Flutter (wget)
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.38.2-stable.tar.xz
          tar xf flutter_linux_3.38.2-stable.tar.xz
          # Set Git safe directory for Flutter path
          git config --global --add safe.directory "$(pwd)/flutter"
          # Set Flutter path
          echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze Formatting
        run: flutter analyze lib test

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y jq 

      - name: Install Flutter (wget)
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.38.2-stable.tar.xz
          tar xf flutter_linux_3.38.2-stable.tar.xz
          # Set Git safe directory for Flutter path
          git config --global --add safe.directory "$(pwd)/flutter"
          # Set Flutter path
          echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test