name: Pull Request Pipeline

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter (wget)
        run: |
          wget --show-progress --progress=bar:force:noscroll:giga https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.38.2-stable.tar.xz
          tar xf flutter_linux_3.38.2-stable.tar.xz
          git config --global --add safe.directory "$(pwd)/flutter"
          echo "$(pwd)/flutter/bin" >> $GITEA_PATH

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze Formatting
        run: flutter analyze lib test

  test:
    runs-on: ubuntu-latest
    env:
      RUNNER_TOOL_CACHE: /toolcache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter (wget)
        run: |
          wget --show-progress --progress=bar:force:noscroll:giga https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.38.2-stable.tar.xz
          tar xf flutter_linux_3.38.2-stable.tar.xz
          git config --global --add safe.directory "$(pwd)/flutter"
          echo "$(pwd)/flutter/bin" >> $GITEA_PATH

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test
