name: Pull Request Pipeline

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:18-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq

      - name: Set Up Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Configure Git Safe Directory
        run: |
          git config --global --add safe.directory /workspace/liquid-development/game-tracker
          git config --global --add safe.directory /workspace/liquid-development/game-tracker/flutter


      - name: Get dependencies
        run: flutter pub get

      - name: Check Formatting
        run: flutter analyze



  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.0'

      - name: Get dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test