name: Push Pipeline

on:
  push:
    branches:
      - "development"
      - "main"

jobs:
  format:
    runs-on: ubuntu-latest
    if: false # Needs bot user
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y jq 

      - name: Install Flutter (wget)
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.38.2-stable.tar.xz
          tar xf flutter_linux_3.38.2-stable.tar.xz
          # Set Git safe directory for Flutter path
          git config --global --add safe.directory "$(pwd)/flutter"
          # Set Flutter path
          echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      - name: Get & upgrade dependencies
        run: |
          flutter pub get
          flutter pub upgrade --major-versions

      - name: Auto-format
        run: |
          dart format lib
          dart fix --apply lib 

        # Needs credentials, push access and the right files need to be staged
      - name: Commit Changes
        run: |
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.com"
         git status
          git add lib/
          git status
          git commit -m "Actions: Auto-formatting [skip ci]"
          git push
